cache: apt
sudo: required

language: python
python:
  - "2.7"
  
virtualenv:
  system_site_packages: true
  
addons:
  apt:
    packages:
    - python-vtk

before_install:
 - sudo apt-get install -qq python-vtk
 - source ~/virtualenv/python2.7_with_system_site_packages/bin/activate
 - travis_retry wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh
 - chmod +x miniconda.sh
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH=/home/travis/virtualenv/python2.7_with_system_site_packages/bin/activate:/home/travis/miniconda/bin:$PATH
 - export PYHTONPATH=/home/travis/virtualenv/python2.7_with_system_site_packages/bin/activate:/home/travis/miniconda/bin:$PYTHONPATH
 - conda update --yes conda

install:
 - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
 - source activate test
 - conda install --yes numpy scipy matplotlib pip nose
 - pip install setuptools
 - pip install enum34
 - pip install numpy-stl
 - pip install coveralls
 - pip install coverage
 - python setup.py install

script: 
 coverage run test.py

after_success:
 - coveralls

branches:
  only:
    - master
